--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: database; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS database;




--
-- Name: databases; Type: TABLE; Schema: database; Owner: -
--

CREATE TABLE database.databases (
    databaseid bigint NOT NULL,
    customerid bigint DEFAULT 0 NOT NULL,
    databasetypeid bigint DEFAULT 1 NOT NULL,
    databasename character varying(255) NOT NULL,
    username character varying(64) DEFAULT ''::character varying NOT NULL,
    password character varying(255) DEFAULT ''::character varying NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    creator character varying(255) DEFAULT ''::character varying NOT NULL,
    updated timestamp with time zone DEFAULT now() NOT NULL,
    updater character varying(255) DEFAULT ''::character varying NOT NULL,
    db_usage bigint DEFAULT 0 NOT NULL
);


--
-- Name: databases_databaseid_seq; Type: SEQUENCE; Schema: database; Owner: -
--

ALTER TABLE database.databases ALTER COLUMN databaseid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME database.databases_databaseid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasetypes; Type: TABLE; Schema: database; Owner: -
--

CREATE TABLE database.databasetypes (
    databasetypeid bigint NOT NULL,
    databasetypename character varying(32) NOT NULL
);


--
-- Name: databasetypes_databasetypeid_seq; Type: SEQUENCE; Schema: database; Owner: -
--

ALTER TABLE database.databasetypes ALTER COLUMN databasetypeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME database.databasetypes_databasetypeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databases databasename_uq; Type: CONSTRAINT; Schema: database; Owner: -
--

ALTER TABLE ONLY database.databases
    ADD CONSTRAINT databasename_uq UNIQUE (databasename);


--
-- Name: databases databases_pk; Type: CONSTRAINT; Schema: database; Owner: -
--

ALTER TABLE ONLY database.databases
    ADD CONSTRAINT databases_pk PRIMARY KEY (databaseid);


--
-- Name: databasetypes databasetypename_uq; Type: CONSTRAINT; Schema: database; Owner: -
--

ALTER TABLE ONLY database.databasetypes
    ADD CONSTRAINT databasetypename_uq UNIQUE (databasetypename);


--
-- Name: databasetypes databasetypes_pk; Type: CONSTRAINT; Schema: database; Owner: -
--

ALTER TABLE ONLY database.databasetypes
    ADD CONSTRAINT databasetypes_pk PRIMARY KEY (databasetypeid);


--
-- Name: databases databases_customerid_fk; Type: FK CONSTRAINT; Schema: database; Owner: -
--

ALTER TABLE ONLY database.databases
    ADD CONSTRAINT databases_customerid_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON DELETE SET DEFAULT;


--
-- Name: databases databases_databasetypeid_fk; Type: FK CONSTRAINT; Schema: database; Owner: -
--

ALTER TABLE ONLY database.databases
    ADD CONSTRAINT databases_databasetypeid_fk FOREIGN KEY (databasetypeid) REFERENCES database.databasetypes(databasetypeid) ON UPDATE CASCADE;


--
-- PostgreSQL database dump complete
--
